groups: []

resource_types:
- name: bosh-creds
  type: docker-image
  source:
    repository: dlapiduz/bosh-creds-resource
    tag: latest
- name: cron
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
    tag: latest

resources:
- name: this-repo
  type: git
  source:
    uri: https://github.com/dlapiduz/bosh-pause.git
    branch: master
- name: om-bosh-creds
  type: bosh-creds
  source:
    pcf_ert_domain: {{pcf_ert_domain}}
    pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
    pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
    opsman_url: {{opsman_url}}
- name: morning-cron
  type: cron
  source:
    expression: "0 10 * * 1-5"
    location: "America/New_York"

- name: night-cron
  type: cron
  source:
    expression: "0 18 * * *"
    location: "America/New_York"


jobs:
- name: manual-stop
  plan:
  - aggregate:
    - get: this-repo
    - get: om-bosh-creds
  - task: start-jobs
    file: this-repo/tasks/bosh-start-stop.yml
    params:
      command: stop
- name: start
  plan:
  - aggregate:
    - get: this-repo
    - get: om-bosh-creds
    - get: morning-cron
      trigger: true
  - task: start-jobs
    file: this-repo/tasks/bosh-start-stop.yml
    params:
      command: start
- name: stop
  plan:
  - aggregate:
    - get: this-repo
    - get: om-bosh-creds
    - get: night-cron
      trigger: true
  - task: start-jobs
    file: this-repo/tasks/bosh-start-stop.yml
    params:
      command: night
