---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker-gcp

inputs:
- name: om-bosh-creds
- name: this-repo

params:
  command:

run:
  path: this-repo/tasks/bosh-start-stop.sh
